engines:
  eslint:
    enabled: true
    fixme: true
ratings:
  paths:
    - "app/src/**/*"
    - "gulp/**/*"
    - "src/**/*"
    - "test/**/*"
#
# ---Exclude Files or Directories---
# List the files or directories you would like excluded from our analysis.
# For help setting your exclude paths:
# http://docs.codeclimate.com/article/166-excluding-files-folders
#
exclude_paths:
  - "dist/*"
